// Generates convex/seedData.ts from the fictional network data that the
// Dream Travel operator-finder demo was built from.
//
// The demo shipped its network as JSON. Convex bundles TypeScript, not JSON, so
// this turns those records into a typed module the seed mutation can read. It is
// a build-time step: re-run it after changing the source data.
//
//   node scripts/build-seed.mjs
//
// Source: C:/Projects/Dream Travel ITO Finder Project/dream-travel-demo/data
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const demo = resolve(
  process.env.DREAM_TRAVEL_DEMO ?? "C:/Projects/Dream Travel ITO Finder Project/dream-travel-demo",
);

const read = (name) => JSON.parse(readFileSync(resolve(demo, "data", name), "utf8"));
const json = (value) => JSON.stringify(value);

const partners = read("partners.json");
const profiles = read("operator-profiles.json");

if (partners.length !== profiles.length)
  throw new Error("Every seeded operator needs exactly one capability profile.");

const operators = partners.map((partner) => ({
  slug: partner.id,
  name: partner.name,
  country: partner.country,
  destinations: partner.destinations,
  specialties: partner.specialties,
  minGroupSize: partner.minGroupSize,
  maxGroupSize: partner.maxGroupSize,
  experienceLevels: partner.experienceLevels,
  typicalNetPriceMin: partner.typicalNetPriceMin,
  typicalNetPriceMax: partner.typicalNetPriceMax,
  // The shipped network's records are complete, so every seeded operator starts
  // with its capability on file rather than pending.
  approvalStatus: "capability_on_file",
  source: "seed",
}));

// The profile's own id is the operator slug; the demo kept a separate partnerId.
const seedProfiles = profiles.map((profile) => {
  const { partnerId, ...rest } = profile;
  return {
    operatorSlug: partnerId,
    ...rest,
    serviceAreas: rest.serviceAreas.map((area) => {
      const { destinationId, ...restArea } = area;
      return { destinationSlug: destinationId, ...restArea };
    }),
  };
});

const header = `// GENERATED by scripts/build-seed.mjs — do not edit by hand.
//
// The fictional incoming tour operator network the demo shipped with: ten
// operators, one capability profile each. Every company, price, blackout period
// and deadline below is invented for demonstration. Nothing here describes a
// real supplier.
import type { Infer } from "convex/values";
import { operatorCapability, operatorRecord } from "./schema";

// The seed carries neither an owner nor timestamps: the seed mutation stamps both
// as it writes, so seeding one workspace never leaks into another, and re-running
// it never makes an untouched record look recently edited.
export type SeedOperator = Omit<
  Infer<typeof operatorRecord>,
  "owner" | "updatedAt"
>;
export type SeedOperatorProfile = Omit<
  Infer<typeof operatorCapability>,
  "owner" | "updatedAt"
>;

`;

const body = [
  `export const seedOperators: SeedOperator[] = ${json(operators).replace(/\},/g, "},\n  ")};`,
  "",
  `export const seedOperatorProfiles: SeedOperatorProfile[] = ${json(seedProfiles).replace(/\},/g, "},\n  ")};`,
  "",
].join("\n");

mkdirSync(resolve(here, "..", "convex"), { recursive: true });
writeFileSync(resolve(here, "..", "convex", "seedData.ts"), header + body, "utf8");

// The advisor's own reference data (destinations and ready-made programs) is not
// stored on the server: it is static, it never changes during a demo, and the
// matching engine reads it synchronously. Keep its field names consistent with
// the stored records.
const programs = read("trips.json").map((trip) => {
  const { partnerId, destinationId, ...rest } = trip;
  return { ...rest, operatorSlug: partnerId, destinationSlug: destinationId };
});
writeFileSync(
  resolve(here, "..", "src", "data", "programs.json"),
  JSON.stringify(programs, null, 2),
  "utf8",
);

console.log(
  `Wrote convex/seedData.ts (${operators.length} operators) and src/data/programs.json (${programs.length} programs).`,
);
